name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install buildozer
        
    - name: Build APK
      run: |
        buildozer init
        sed -i "s/^requirements = .*/requirements = python3,kivy/" buildozer.spec
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: bin/*.apk