name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev libtinfo-dev cmake libffi-dev libssl-dev wget
        pip install buildozer cython
        
    - name: Install Android Command Line Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        echo "$PWD/cmdline-tools/latest/bin" >> $GITHUB_PATH
        
    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/android-sdk-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> ~/.android/android-sdk-license
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> ~/.android/android-sdk-license
        
    - name: Install Android SDK
      run: |
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        # 安装指定版本的构建工具（兼容Kivy）
        sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platform-tools" "platforms;android-34"
        
    - name: Build APK
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        # 更新buildozer.spec配置
        sed -i "s/^requirements = .*/requirements = python3,kivy/" buildozer.spec
        sed -i "s/^android.sdk_build_tools = .*/android.sdk_build_tools = 34.0.0/" buildozer.spec
        sed -i "s/^android.ndk_version = .*/android.ndk_version = 23b/" buildozer.spec
        
        # 添加缺失的AIDL路径到环境变量
        echo "PATH=$PATH:$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_ENV
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp
        path: bin/*.apk